title		: CodeRevisited
description	: Keep Learning.. Cheers!!!

owner:
 name	: Suresh Sajja
 avatar	: suresh.jpg
 bio	: "Passionate Software Engineer"
 email	: mail@sureshsajja.com
 github	: sureshsajja		


#url: "http://ec2-52-32-183-180.us-west-2.compute.amazonaws.com/" # EC2 URL
url: "https://sureshsajja.github.io" # Github URL

# Build settings
markdown: kramdown
host: 0.0.0.0
port: 80
gems:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed
